//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalaryManagementWeb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SALARY_MANAGEMENTEntities : DbContext
    {
        public SALARY_MANAGEMENTEntities()
            : base("name=SALARY_MANAGEMENTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CompanyRoles> CompanyRoles { get; set; }
        public DbSet<Projects> Projects { get; set; }
        public DbSet<Employee> Employee { get; set; }
    }
}
